export const TIDE_GRAPH_COMPACT_X_SIZE = 50;
export const TIDE_GRAPH_X_SIZE = 80;
export const TIDE_GRAPH_Y_SIZE = 800;

export const TIDE_GRAPH_PERIOD_GUTTER = 12;

export const TEAM_STROKE_COLOR_LIGHTEN_PERCENT = 20;
